/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedCompetitorDiscoveryRouteImport } from './routes/_authenticated/competitor-discovery'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated/pages'
import { Route as AuthenticatedProblemsBenefitsRouteImport } from './routes/_authenticated/problems-benefits'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTop10RouteImport } from './routes/_authenticated/top10'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin/accounts'
import { Route as AuthenticatedAdminCashNumbersRouteImport } from './routes/_authenticated/admin/cash-numbers'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin/maintenance'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin/pricing'
import { Route as ApiPublicDebugTokenRouteImport } from './routes/api/public/debug-token'
import { Route as ApiPublicCompetitorCollectTickRouteImport } from './routes/api/public/competitor-collect/tick'
import { Route as ApiPublicEmergencyRecheckTickRouteImport } from './routes/api/public/emergency-recheck/tick'
import { Route as ApiPublicGithubWebhookRouteImport } from './routes/api/public/github/webhook'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs/tick'
import { Route as ApiPublicPbReviewTickRouteImport } from './routes/api/public/pb-review/tick'
import { Route as ApiPublicPricingSyncRouteImport } from './routes/api/public/pricing/sync'
import { Route as ApiPublicProductCrawlRunRouteImport } from './routes/api/public/product-crawl/run'
import { Route as ApiPublicRawAdsAnalyzeTickRouteImport } from './routes/api/public/raw-ads-analyze/tick'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitorDiscoveryRoute =
  AuthenticatedCompetitorDiscoveryRouteImport.update({
    id: '/competitor-discovery',
    path: '/competitor-discovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsBenefitsRoute =
  AuthenticatedProblemsBenefitsRouteImport.update({
    id: '/problems-benefits',
    path: '/problems-benefits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTop10Route = AuthenticatedTop10RouteImport.update({
  id: '/top10',
  path: '/top10',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCashNumbersRoute =
  AuthenticatedAdminCashNumbersRouteImport.update({
    id: '/cash-numbers',
    path: '/cash-numbers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicDebugTokenRoute = ApiPublicDebugTokenRouteImport.update({
  id: '/api/public/debug-token',
  path: '/api/public/debug-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompetitorCollectTickRoute =
  ApiPublicCompetitorCollectTickRouteImport.update({
    id: '/api/public/competitor-collect/tick',
    path: '/api/public/competitor-collect/tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmergencyRecheckTickRoute =
  ApiPublicEmergencyRecheckTickRouteImport.update({
    id: '/api/public/emergency-recheck/tick',
    path: '/api/public/emergency-recheck/tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGithubWebhookRoute = ApiPublicGithubWebhookRouteImport.update({
  id: '/api/public/github/webhook',
  path: '/api/public/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs/tick',
  path: '/api/public/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPbReviewTickRoute = ApiPublicPbReviewTickRouteImport.update({
  id: '/api/public/pb-review/tick',
  path: '/api/public/pb-review/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPricingSyncRoute = ApiPublicPricingSyncRouteImport.update({
  id: '/api/public/pricing/sync',
  path: '/api/public/pricing/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductCrawlRunRoute =
  ApiPublicProductCrawlRunRouteImport.update({
    id: '/api/public/product-crawl/run',
    path: '/api/public/product-crawl/run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRawAdsAnalyzeTickRoute =
  ApiPublicRawAdsAnalyzeTickRouteImport.update({
    id: '/api/public/raw-ads-analyze/tick',
    path: '/api/public/raw-ads-analyze/tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/ads': typeof AuthenticatedAdsRoute
  '/competitor-discovery': typeof AuthenticatedCompetitorDiscoveryRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/problems-benefits': typeof AuthenticatedProblemsBenefitsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/top10': typeof AuthenticatedTop10Route
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/cash-numbers': typeof AuthenticatedAdminCashNumbersRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/api/public/debug-token': typeof ApiPublicDebugTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/competitor-collect/tick': typeof ApiPublicCompetitorCollectTickRoute
  '/api/public/emergency-recheck/tick': typeof ApiPublicEmergencyRecheckTickRoute
  '/api/public/github/webhook': typeof ApiPublicGithubWebhookRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/pb-review/tick': typeof ApiPublicPbReviewTickRoute
  '/api/public/pricing/sync': typeof ApiPublicPricingSyncRoute
  '/api/public/product-crawl/run': typeof ApiPublicProductCrawlRunRoute
  '/api/public/raw-ads-analyze/tick': typeof ApiPublicRawAdsAnalyzeTickRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/competitor-discovery': typeof AuthenticatedCompetitorDiscoveryRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/problems-benefits': typeof AuthenticatedProblemsBenefitsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/top10': typeof AuthenticatedTop10Route
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/cash-numbers': typeof AuthenticatedAdminCashNumbersRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/api/public/debug-token': typeof ApiPublicDebugTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/competitor-collect/tick': typeof ApiPublicCompetitorCollectTickRoute
  '/api/public/emergency-recheck/tick': typeof ApiPublicEmergencyRecheckTickRoute
  '/api/public/github/webhook': typeof ApiPublicGithubWebhookRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/pb-review/tick': typeof ApiPublicPbReviewTickRoute
  '/api/public/pricing/sync': typeof ApiPublicPricingSyncRoute
  '/api/public/product-crawl/run': typeof ApiPublicProductCrawlRunRoute
  '/api/public/raw-ads-analyze/tick': typeof ApiPublicRawAdsAnalyzeTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/competitor-discovery': typeof AuthenticatedCompetitorDiscoveryRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/pages': typeof AuthenticatedPagesRoute
  '/_authenticated/problems-benefits': typeof AuthenticatedProblemsBenefitsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/top10': typeof AuthenticatedTop10Route
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/cash-numbers': typeof AuthenticatedAdminCashNumbersRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/api/public/debug-token': typeof ApiPublicDebugTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/competitor-collect/tick': typeof ApiPublicCompetitorCollectTickRoute
  '/api/public/emergency-recheck/tick': typeof ApiPublicEmergencyRecheckTickRoute
  '/api/public/github/webhook': typeof ApiPublicGithubWebhookRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/pb-review/tick': typeof ApiPublicPbReviewTickRoute
  '/api/public/pricing/sync': typeof ApiPublicPricingSyncRoute
  '/api/public/product-crawl/run': typeof ApiPublicProductCrawlRunRoute
  '/api/public/raw-ads-analyze/tick': typeof ApiPublicRawAdsAnalyzeTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ads'
    | '/competitor-discovery'
    | '/competitors'
    | '/discovery'
    | '/pages'
    | '/problems-benefits'
    | '/products'
    | '/settings'
    | '/top10'
    | '/wallet'
    | '/admin/accounts'
    | '/admin/cash-numbers'
    | '/admin/finance'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/pricing'
    | '/api/public/debug-token'
    | '/admin/'
    | '/api/public/competitor-collect/tick'
    | '/api/public/emergency-recheck/tick'
    | '/api/public/github/webhook'
    | '/api/public/jobs/tick'
    | '/api/public/pb-review/tick'
    | '/api/public/pricing/sync'
    | '/api/public/product-crawl/run'
    | '/api/public/raw-ads-analyze/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ads'
    | '/competitor-discovery'
    | '/competitors'
    | '/discovery'
    | '/pages'
    | '/problems-benefits'
    | '/products'
    | '/settings'
    | '/top10'
    | '/wallet'
    | '/'
    | '/admin/accounts'
    | '/admin/cash-numbers'
    | '/admin/finance'
    | '/admin/maintenance'
    | '/admin/payments'
    | '/admin/pricing'
    | '/api/public/debug-token'
    | '/admin'
    | '/api/public/competitor-collect/tick'
    | '/api/public/emergency-recheck/tick'
    | '/api/public/github/webhook'
    | '/api/public/jobs/tick'
    | '/api/public/pb-review/tick'
    | '/api/public/pricing/sync'
    | '/api/public/product-crawl/run'
    | '/api/public/raw-ads-analyze/tick'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ads'
    | '/_authenticated/competitor-discovery'
    | '/_authenticated/competitors'
    | '/_authenticated/discovery'
    | '/_authenticated/pages'
    | '/_authenticated/problems-benefits'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/top10'
    | '/_authenticated/wallet'
    | '/_authenticated/'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/cash-numbers'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/pricing'
    | '/api/public/debug-token'
    | '/_authenticated/admin/'
    | '/api/public/competitor-collect/tick'
    | '/api/public/emergency-recheck/tick'
    | '/api/public/github/webhook'
    | '/api/public/jobs/tick'
    | '/api/public/pb-review/tick'
    | '/api/public/pricing/sync'
    | '/api/public/product-crawl/run'
    | '/api/public/raw-ads-analyze/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDebugTokenRoute: typeof ApiPublicDebugTokenRoute
  ApiPublicCompetitorCollectTickRoute: typeof ApiPublicCompetitorCollectTickRoute
  ApiPublicEmergencyRecheckTickRoute: typeof ApiPublicEmergencyRecheckTickRoute
  ApiPublicGithubWebhookRoute: typeof ApiPublicGithubWebhookRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
  ApiPublicPbReviewTickRoute: typeof ApiPublicPbReviewTickRoute
  ApiPublicPricingSyncRoute: typeof ApiPublicPricingSyncRoute
  ApiPublicProductCrawlRunRoute: typeof ApiPublicProductCrawlRunRoute
  ApiPublicRawAdsAnalyzeTickRoute: typeof ApiPublicRawAdsAnalyzeTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitor-discovery': {
      id: '/_authenticated/competitor-discovery'
      path: '/competitor-discovery'
      fullPath: '/competitor-discovery'
      preLoaderRoute: typeof AuthenticatedCompetitorDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages': {
      id: '/_authenticated/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AuthenticatedPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems-benefits': {
      id: '/_authenticated/problems-benefits'
      path: '/problems-benefits'
      fullPath: '/problems-benefits'
      preLoaderRoute: typeof AuthenticatedProblemsBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/top10': {
      id: '/_authenticated/top10'
      path: '/top10'
      fullPath: '/top10'
      preLoaderRoute: typeof AuthenticatedTop10RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cash-numbers': {
      id: '/_authenticated/admin/cash-numbers'
      path: '/cash-numbers'
      fullPath: '/admin/cash-numbers'
      preLoaderRoute: typeof AuthenticatedAdminCashNumbersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/debug-token': {
      id: '/api/public/debug-token'
      path: '/api/public/debug-token'
      fullPath: '/api/public/debug-token'
      preLoaderRoute: typeof ApiPublicDebugTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/competitor-collect/tick': {
      id: '/api/public/competitor-collect/tick'
      path: '/api/public/competitor-collect/tick'
      fullPath: '/api/public/competitor-collect/tick'
      preLoaderRoute: typeof ApiPublicCompetitorCollectTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emergency-recheck/tick': {
      id: '/api/public/emergency-recheck/tick'
      path: '/api/public/emergency-recheck/tick'
      fullPath: '/api/public/emergency-recheck/tick'
      preLoaderRoute: typeof ApiPublicEmergencyRecheckTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/webhook': {
      id: '/api/public/github/webhook'
      path: '/api/public/github/webhook'
      fullPath: '/api/public/github/webhook'
      preLoaderRoute: typeof ApiPublicGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tick': {
      id: '/api/public/jobs/tick'
      path: '/api/public/jobs/tick'
      fullPath: '/api/public/jobs/tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pb-review/tick': {
      id: '/api/public/pb-review/tick'
      path: '/api/public/pb-review/tick'
      fullPath: '/api/public/pb-review/tick'
      preLoaderRoute: typeof ApiPublicPbReviewTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pricing/sync': {
      id: '/api/public/pricing/sync'
      path: '/api/public/pricing/sync'
      fullPath: '/api/public/pricing/sync'
      preLoaderRoute: typeof ApiPublicPricingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-crawl/run': {
      id: '/api/public/product-crawl/run'
      path: '/api/public/product-crawl/run'
      fullPath: '/api/public/product-crawl/run'
      preLoaderRoute: typeof ApiPublicProductCrawlRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/raw-ads-analyze/tick': {
      id: '/api/public/raw-ads-analyze/tick'
      path: '/api/public/raw-ads-analyze/tick'
      fullPath: '/api/public/raw-ads-analyze/tick'
      preLoaderRoute: typeof ApiPublicRawAdsAnalyzeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminCashNumbersRoute: typeof AuthenticatedAdminCashNumbersRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
    AuthenticatedAdminCashNumbersRoute: AuthenticatedAdminCashNumbersRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedCompetitorDiscoveryRoute: typeof AuthenticatedCompetitorDiscoveryRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRoute
  AuthenticatedProblemsBenefitsRoute: typeof AuthenticatedProblemsBenefitsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTop10Route: typeof AuthenticatedTop10Route
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedCompetitorDiscoveryRoute: AuthenticatedCompetitorDiscoveryRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedPagesRoute: AuthenticatedPagesRoute,
  AuthenticatedProblemsBenefitsRoute: AuthenticatedProblemsBenefitsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTop10Route: AuthenticatedTop10Route,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDebugTokenRoute: ApiPublicDebugTokenRoute,
  ApiPublicCompetitorCollectTickRoute: ApiPublicCompetitorCollectTickRoute,
  ApiPublicEmergencyRecheckTickRoute: ApiPublicEmergencyRecheckTickRoute,
  ApiPublicGithubWebhookRoute: ApiPublicGithubWebhookRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
  ApiPublicPbReviewTickRoute: ApiPublicPbReviewTickRoute,
  ApiPublicPricingSyncRoute: ApiPublicPricingSyncRoute,
  ApiPublicProductCrawlRunRoute: ApiPublicProductCrawlRunRoute,
  ApiPublicRawAdsAnalyzeTickRoute: ApiPublicRawAdsAnalyzeTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
